# permissions for end users to view manifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manifests-viewer-role
rules:
- apiGroups:
  - entangle-proxy.c3os-x.io
  resources:
  - manifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - entangle-proxy.c3os-x.io
  resources:
  - manifests/status
  verbs:
  - get
