# permissions for end users to edit manifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manifests-editor-role
rules:
- apiGroups:
  - entangle-proxy.kairos.io
  resources:
  - manifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - entangle-proxy.kairos.io
  resources:
  - manifests/status
  verbs:
  - get
