---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - entangle-proxy.kairos.io
  resources:
  - manifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - entangle-proxy.kairos.io
  resources:
  - manifests/finalizers
  verbs:
  - update
- apiGroups:
  - entangle-proxy.kairos.io
  resources:
  - manifests/status
  verbs:
  - get
  - patch
  - update
